version: '3'
services:

  shrinky: 
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
        - "5000:5000"
    environment:
      MONGO_CONN: "mongodb://admin:admin@mongo:27017"
    depends_on:
      - mongo
  
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: shrinkurls 
